services:
  - type: web
    name: imgur-album-owner
    env: node
    region: singapore
    plan: free
    branch: main
    startCommand: node .output/server/index.mjs
    buildCommand: npm install && npm run build
    envVars:
    - key: NITRO_PRESET
      value: render-com
    - key: NUXT_IMGUR_REFRESH_TOKEN
      sync: false
    - key: NUXT_IMGUR_CLIENT_ID
      sync: false
    - key: NUXT_IMGUR_CLIENT_SECRET
      sync: false
    - key: NUXT_IMGUR_ALBUM_ID
      sync: false